### PR TITLE
Add oracle java jai imageio

### PR DESCRIPTION
**Pull request by alexgleith**
Hey, I updated this to use the methodology that I ended up with for my production GeoServer setup.

It uses Oracle Java, which is faster, and includes ImageIO and JAI extensions for Java.

It also used Supervisor to run Tomcat, which restarts it when it crashes.

Feel free to ignore it or include it. I tested it and it all works. Up to you if you want to pull it in.

### CODE REVIEW

**Comment by srstsavage** [comment]
@alexgleith First of all, thanks for the teamwork here on making this GeoServer docker image more robust. Your idea to add the JAI/ImageIO extensions is great and will definitely result in increased performance.

I'm not going to merge this outright, because 1) I don't think Oracle Java should be used outright due to licensing issues and 2) I don't think that supervisor should be used here.

Regarding Oracle Java, I'm working on a way to use a Docker build-arg to indicate that the Oracle JRE should be used (which will also uninstall the OpenJDK). This should make it easy for users building the image to opt for Oracle Java while allowing the prebuilt image with OpenJDK Java to be hosted on Docker Hub (which should suffice for users with simple/low performance needs or just experimenting with GeoServer).

Usually supervisor is used when multiple processes need to be run in Docker, which isn't the case here. The downside with supervisor is that it becomes the process Docker watches, i.e. `docker logs` watches the supervisor logs instead of Tomcat. There's a JAVA_OPTS flag that allows you to execute a process on OutOfMemory, which can kill the Tomcat process and should end the container execution, which will allow Docker's restart policy to automatically restart the container. I'll add this to the README.

This will also keep this Dockerfile out of the business of installing and managing Tomcat (can still inherit from upstream tomcat:8.0 image), which is better for maintainability into the future.

Once I get the Oracle rewrites in there (later tonight, hopefully), can you give me separate pull requests with just the JAI/ImageIO stuff and the fix up of the build.sh script?

Thanks again!

**Comment by alexgleith** [comment]
Ok, fair enough. You're right that this is the correct way to do things.

Let me know when you're ready and I'll add in the JAI/ImageIO stuff.

For my info, how would you run tomcat? When I ran the original image, it wasn't clear how to start tomcat...

**Comment by srstsavage** [comment]
Great, thanks!

Since this image inherits from the tomcat:8.0 image, it [runs Tomcat on startup already](https://github.com/docker-library/tomcat/blob/ed98c30c1cd42c53831f64dffa78a0abf7db8e9a/8-jre7/Dockerfile#L40):

``` Dockerfile
CMD ["catalina.sh", "run"]
```

**Comment by srstsavage** [comment]
@alexgleith Ok, ready for those PRs. In the updated Dockerfile, the JAI/ImageIO installation should happen at line 55, right after the Oracle JDK installation and before the Geoserver installation. As long as you install to `$JAVA_HOME` as you're already doing it should install to either the OpenJDK or Oracle JDK. If you change WORKDIR, please set it back using `WORKDIR $CATALINA_HOME` when you're finished. 

See the [Oracle JDK section of the README](https://github.com/shane-axiom/docker-geoserver#building-with-oracle-jdk) for more on building with the Oracle JDK.

Thanks again!

**Comment by srstsavage** [comment]
@alexgleith Do you think you'll have time to submit those PRs in the next few days? I'd like to get everything merged back to the main repo this week but I want you to get commit credit for the JAI/ImageIO installation...

**Comment by alexgleith** [comment]
Yep, give me a couple of hours and I'll sort it.

**Comment by alexgleith** [comment]
Hey, I pushed in two PRs.

https://github.com/shane-axiom/docker-geoserver/pull/3

and

https://github.com/shane-axiom/docker-geoserver/pull/2

The bottom one has the JAI stuff. I haven't tested yet, as where I am the
internet has gone to crap (undersea cable was cut the other day...) but I
am testing slowly and if I find any issues I'll add to the PR.

**Pull request closed without merging**
